apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: simple-app
  namespace: flux-system
spec:
  images:
    - name: index.docker.io/janakiramm/simple-acorn-app
      newName: index.docker.io/janakiramm/simple-acorn-app
      newTag: 1.0.0 # {"$imagepolicy": "flux-system:app-policy:tag"}
