apiVersion: api.acorn.io/v1
kind: App
metadata:
  name: restless-pine
  namespace: acorn
spec:
  image: index.docker.io/janakiramm/simple-acorn-app:v1.0.0
  ports:
  - publish: true
    targetPort: 80
