---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  releaseName: metallb
  targetNamespace: metallb-system
  chart:
    sourceRef:
      kind: HelmRepository
      name: metallb
      namespace: flux-system
  interval: 1m0s