---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 3m
  targetNamespace: ingress-nginx
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name:  nginx-ingress
        namespace: nginx-ingress
      interval: 1m
