apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: simple-app
  namespace: flux-system
spec:
  dependsOn:
    - name: acorn  
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./application
  prune: true
  wait: true
