apiVersion: api.acorn.io/v1
kind: App
metadata:
  name: simple-app
  namespace: acorn
spec:
  image: index.docker.io/janakiramm/simple-acorn-app:v1.0.1 # {"$imagepolicy": "flux-system:app-policy"}
  ports:
  - publish: true
    targetPort: 80
